### PR TITLE
lecture 13 group A skarten skailas

### PR DESCRIPTION
**Pull request by sethkarten**
skarten and skailas
lecture 13 group A scribe with 1 page appendix (EC)

### CODE REVIEW

**Comment by sethkarten** [comment]
lecture 14 D skarten skailas here as well

**Comment by kshitijgoel007** [comment]
### Feedback for 13A
Nothing major. Algorithm presentation and the comparison between EXP3 and EXP4 is reasonable.
Thanks for adding an appendix on markov chains.

### Notes to the TA
Submitted within deadline. One page EC.

**Comment by kshitijgoel007** [comment]
Attn:@lagrassa : 14D scribe submission is in here as well. I will merge this once you comment with 14D comments.

**Comment by lagrassa** [comment]
### Review
1. Summarizes relationship between bandit problems and RL setting
2. Overviews key concepts of EXP3/EXP4/Thompson sampling

### Summary
1. Goes through table of different classes of learning problems and explains whether each is sampled, evaluative, sequential
2. Characterizes MDPs using the factorization and different types of rewards
3. Would have been nice to include a "Markov blanket" type thing for students who are not familiar with factorization but writing it out in Section 3.3 does a lot of that, which is good since Kris was worried some people didn't have that background. 
4. Shows derivation of the recursive form of the value and state-value function.
5. Contrasts optimality eq. and bellman eq

### Grading notes
1. Submitted within deadline
2. High-quality notes (though page length short)
3. No extra information

**Pull request merged**
