### PR TITLE
Lecture 16 Group C - Michelle

### PR DESCRIPTION
**Pull request by mzhao98**
Lecture 16 Group C - Michelle

### CODE REVIEW

**Review by lagrassa — CHANGES_REQUESTED** [review]
### Review
1. Nice job putting this lecture in context in the summary
1. Expands on the RL method taxonomy figure from lecture
1. Summarizes value iteration and policy iteration

### Summary
1. Somewhat incorrect characterization of model-based and model-free that I'd like you to correct. In model-based control, the agent might not have access to a fully-specified model. In fact, typically when someone refers to "MBRL" part of the problem is estimating the model. This might have been confusing from how I presented Value-based model based control. The key difference is in model-free control, generally, there is no attempt to use $T$ or $R$. In MBRL, the agent typically estimates $T$ or $R$ then uses that for control.
1. Please number equations like the one at the end of 2.1 (optional but very helpful and shouldn't take long)
1. Generally, writing out the marginalization is helpful; Kris has been worried that this is a point of confusion. I think there's either a typo or notation I'm not familiar with however in $p(s',r|s,a)$. What is $p$ in the expectation? If you are given $[s', a, s]$, then $r$ is given by $r(s',a,s)$ so why is there a sum over possible rewards? There should be only 1 reward. Please either correct or explain why this is correct in the comment.
1. Usually, system identification means something really specific which is estimating a few parameters in a dynamics equation. What you wrote is more commonly referred to as "Model-based RL", though lecture slides do call it SysID. Up to you what you want to do with this here.
1. Justifies and writes out the pseudocode for each of the MC prediction algorithms. Nice justifications going from one version to another, justifying why each of the changes is made.
1. Good justification for TD from MC. I think an important point missing explicitly is the bias-variance tradeoff for TD. Bootstrapping is both helpful and harmful for the V estimates but it wuld be good to explicitly state why.
1. Justification for N-Step TD prediction is copy-pasted and I think you forgot to update. Please remember to do that in the CR.
1. Similar mischaracterization of MB vs MF RL in the Summary. MBRL research often does not assume access to a correct model (and sometimes no model)

### Grading notes
1. Minor content changes needed for full credit
1. No extra material

~~Very minor change requests (should take 5-10 min to complete)~~
~~If you could delete .DS_Store that would be great but if not I can do it manually when I merge.~~

~~### Review~~
~~1. Reviews VI and PI~~
~~1. Includes taxonomy of RL approaches and places lecture in context of syllabus reasonably~~
~~1. "Value-based control consists of policy evaluation and policy improvement steps" -> this part is a bit of an over-generalization. The 2 methods we showed for value-based control do policy evaluation and policy iteration, but all that's required in value-based control is that a value function is being used to select actions. Please remove or make this sentence more specific in the CR~~

~~### Summary~~
~~1. System identification typically refers to the much more specific problem where certain parameters in a dynamics equation are estimated. You can call this "model-based RL" (though that lecture slide does seem to use those terms interchangeably). Then it's a model-based *control* problem rather than a *prediction* problem. The use of these keywords is important so please fix and make sure you're using them consistently~~
~~1. Characterizes the matrix of MF methods from class~~
~~1. The "test driving" analogy is helpful~~
~~1. Describes first visit mc-prediction working principle~~
~~1. Explains why we use $\alpha$ in the incremental version~~
~~1. Nice justification for Every Visit MC Prediction~~
~~1. Summary of MC prediction~~
~~1. Connects 1-step TD to MC using N=T-t example~~
~~1. Good characterization of N-step TD~~
~~1. Would be good to characterize where the bias comes from in N-step TD since that is a really important characteristic of it. It would be worth noting something about how you trade off variance for higher bias with N-step TD.~~

~~### Grading notes~~
~~Submitted on time, no extra material~~

**Comment by mzhao98** [comment]
Scribe notes updated per the above review, thanks!

**Comment by lagrassa** [comment]
Oh no! I swapped your comments with the other Lecture 16 group.

**Comment by lagrassa** [comment]
Fixed comment. Please update by next Tuesday! Some of the comments were addressed but I believe others still need fixing.

**Comment by mzhao98** [comment]
Scribe notes updated. Addressed comments in change request.

**Review by lagrassa — APPROVED** [review]

**Pull request merged**
