### PR TITLE
Adding scribe notes here for Lecture 10 Group B

### PR DESCRIPTION
**Pull request by SarthakJShetty**
Adding the scribe notes for Prof. Kitani's 02/22/2022 lecture on SVMs. Prepared with @rishabhpahuja. Closed the previous [pull request](https://github.com/kshitijgoel007/16831-Spring-2022/pull/20) because I incorrectly named the lecture as Lecture 9. Please let us know if there are any comments or suggestions.

### CODE REVIEW

**Review by lagrassa — CHANGES_REQUESTED** [review]
### Review ###
1. Previous lecture topics are very broad. The review for these scribe notes should
focus primarily on the previous lecture (which was on OGD).
1. Review material here was largely focused on material that was introduced in this
lecture.
1. Please resubmit with a review section that is approx. 1 page, and contains references to material from the previous lecture, especially material that is referenced in this set of scribe notes.
1. Figures 1 and 2 were directly copied from the lecture slides. Please recreate graphics.
1. Good explanation of how OL can be used for supervised learning.

### Summary ###
1. Good deriving the distance between the origin line, and between lines, going thru
gh all the steps.
1. Figures are all screenshots from the lecture slides. Please recreate the graphics
 in the summary as well.
1. Is the Online SVM section (2)  not part of the Summary (3)?
1. Missing the constraints in Eq. 13, or are there not supposed to be?
1. References to the figure were helpful, but refer to figure 3. If you use latex la
bels, it should remove the potential for error when figure numbers change.
1. Notes use $\chi$ though figures and class use $\xi$. Please make these consistent
. In general, it is best to use the notation we used in class unless you justify a new notation, but at the very least the notation used in the text should match the figures.
1. $\chi$ in your notes isn't a tunable parameter though the notes state that "The v
alue of $\chi$ needs to be tuned as a very large value might miss-classify all the v
arables"
1. "something called as sub-gradient which is like online gradient descent but is more flexible" really should be more specific, but from context it's possible to tell
that the differentiability of Eq. 20 is why you need to use subgradients.
1. Language at the end comparing perceptron and SVM is very informal. Algorithms don
't "care'", but you can just update this in future scribe notes.
1. Thanks for mentioning that you referenced previous years scribe notes.

### Outside Info ###
N/A

### Grading notes ###
- On-time, no outside info
- Initial submission needs changes for review and for figures

**Comment by SarthakJShetty** [comment]
@lagrassa thanks for the comments, we will review them and re-submit. @rishabhpahuja, we need to update some of the content, see previous comment.

**Comment by lagrassa** [comment]
When is a reasonable timeline for you to resubmit?

**Comment by SarthakJShetty** [comment]
Hey @lagrassa, you can expect our updated notes by Wednesday (03/16/2022). We had three deadlines this week and another 2 next week. Apologies for the delay. Thanks!

**Comment by SarthakJShetty** [comment]
Hey @lagrassa we've incorporated the changes that you mentioned to our scribes. Please let us know if there are any other changes. This is the latest commit: https://github.com/kshitijgoel007/16831-Spring-2022/pull/21/commits/d69bddf4594de5f4555770eb6828885bf563e515.
Thanks!

**Comment by lagrassa** [comment]
Thanks. Merged, though will take some time to update in gradescope.

**Pull request merged**
