### PR TITLE
add lecture 11 from group A, Yimin Tang and Zilin Si

### PR DESCRIPTION
**Pull request by Si-Lynnn**

### CODE REVIEW

**Comment by kshitijgoel007** [comment]
## Feedback
1. The toy example figure is created (Figure 1) but never discussed in the text. Please add an explanation.
2. There are inconsistencies in symbols in Eqs. 4 -- 6. Specifically, what is the difference between $$w$$ and $$\mathbf{w}$$?
3. Remove `1.5em 0pt` from the top of the PDF.

## Notes to the TA
Submitted within deadline. No major external information.

**Review by kshitijgoel007 — CHANGES_REQUESTED** [review]
Please address the changes given in the feedback.

**Comment by Si-Lynnn** [comment]
Hi TA, thanks for the comments. We have committed the new version. However, it says conflicts (src/.DS_Store) need to be resolved but I don't have access to resolve it. Is there anything I can do or could you help with it? Thank you!

**Comment by kshitijgoel007** [comment]
Thanks for the changes. Don’t worry about the conflicts; I’ll take care of
it.

**Review by kshitijgoel007 — APPROVED** [review]

**Pull request closed without merging**
