### PR TITLE
Scribes for Lecture 4 by Group A (Roshini Rajesh Kannan , Moneish Kumar)

### PR DESCRIPTION
**Pull request by moneishkumar**
Added .tex , .bib and .pdf file all titled Lecture_4_A

### CODE REVIEW

**Comment by lagrassa** [comment]
### Feedback
**Review Section**
1.  Good paraphrasing the PWEA characterization as an online learning problem
2. "we calculated mistake bound with tells the cost of deviation for not following the perfect hypothesis"  this is not a correct definition. A mistake bound is an upper bound on the number of mistakes. Please fix this definition. It sounds like you're defining regret here. 
3. Careful with terminology here "at least one perfect algorithm" - regret is not about the algorithm here; if the algorithm in this context is WMA. Please fix this statement as well.
4.  I don't know if I agree with the statement that "regret bound is a general performance bound and mistake bound is a special case of it". 
3. "The mistake bound of the halving algorithm...." - this would be a good place to include the actual mistake bound since we derived it.  (Optional)


**Summary Section**
1. The lower bound function is derived using the fact that a single element is always greater than or
equal to the sum. - This theorem requires to include one more additional assumption on the weights, which you can reference in the rest of the notes but don't here. It would be good to change that the first time you use the theorem that a single element is upper bounded by the sum. 
2. Small but significant important typo: you state "a single element is always greater than or equal to the sum" but use a \leq in Equation 8. Please fix the text to match the math. 
2. You can describe WMA's mistake bound to be a little tighter than m_n when you define it as the # of mistakes made by the best expert. That connection is made in the lecture but not as much in the notes. You don't need to change this one if you don't want to though. 
3. Good justification to transition to the RWMA section. 
4. Good proof in Appendix B but Appendix A is incomplete. Why and how small are "these values" and why won't they be greater than $$-x-x^2$$?

**Outside Information**
N/A

### Notes for the TA
Submitted within 3 days
Did not include additional outside info.

**Review by lagrassa — CHANGES_REQUESTED** [review]
Minor changes requested in a comment. Please update by Friday 2/11.

**Comment by moneishkumar** [comment]
Update the changes, kindly have a look at them

**Comment by lagrassa** [comment]
Better, thanks!

**Pull request merged**
