### PR TITLE
Scribe Notes of Lecture 14 (Monday, March 14), Group C (Xuanbai Chen, Jia Shi)

### PR DESCRIPTION
**Pull request by Xuanbai-Chen**
Hi,

This is the Scribe Notes of Lecture 14 (Monday, March 14), from Group C (Xuanbai Chen, Jia Shi)

Best,
Xuanbai.

### CODE REVIEW

**Review by lagrassa — CHANGES_REQUESTED** [review]
The submitted notes are generally thorough and helpful comments throughout to add to content from lecture. Some minor changes requested plus figures need to be recreated according to course policy.  Figures do not need to be polished. Hand-drawn is fine, as long as they are "in your own words". Please resubmit by Friday March 25 (can be later if you let me know when) for full credit. 

### Review
1. Includes algorithm for Thompson sampling , includes the regret bound 
1. Important typo on line 8 of Algorithm 3, please fix.
1. (optional) In the future, please include a 1 line description of the algorithms working principle instead of just 
including the pseudocode. 
1. (optional) Context is never defined and is a common point of confusion. Ideally point out what the 
``context'' is in EXP4, and briefly define it.
1. An important connection in the review is the difference between the problems EXP3/EXP4
addresses and sequence feedback. This is included in the first part of the summary, which
is reasonable since it was in the lecture. 

### Summary
1. The one-shot/sequential comparison is  important. The intutive explanation given in 
2.1 is good, but please change the subsection headings to be a little more specific: you're really
comparing one-shot and sequential learning.
1. Nice discussion of the comparison of the algorithms using table 1. 
1. Nice examples/descriptions for the components of MDPs
1. Figure 3 is screenshotted from the lecture slides and needs to be recreated. You can
include just a small subset of it based on the text description.
1. Figure 4 also copied. You can also refer to it in Section 2.2
1. Explains why $$V^{\pi}(s) = \sum_a \pi(a|s) Q^{\pi}(s,a)$$
1. Figure 5 copied. When you recreate it, you can use the descriptions you give in the paragraph.
1. Derives Bellman eq, Bellman optimal equality equation and describes all steps

### Additional info
1. Describes the challenges of solving RL on basic MDPs, then proposes solving them with 
factored MDPs

1. Mentions 2 different representations used for FMDPs

1. States an using DTs algorithm on DBNs, how it forms abstractions, and its limitations
1. Then mentions and algorithm that uses Algebraic Decision Diagrams to represent the VF.
1. Defines and states algorithms for weakly coupled FMDPS

### Grading notes
1. Submitted on time
1. approx 1.2 pages of supplementary material (extra credit)
1. Figures screenshotted from lecture slides, needs to be updated for full credit

**Comment by Xuanbai-Chen** [comment]
Can you extend the deadline to next week since we have three deadlines which belong to different course this week (3.24, 3.25, 3.26)? Thank you very much.

**Comment by lagrassa** [comment]
Of course, waiting on changes, deadline extension requested on Piazza.

**Comment by Xuanbai-Chen** [comment]
Hi Alex,

Thank you for waiting! I have modified the Scribe Notes based on your valuable instructions .

Review:
1.Thompson sampling algorithm has been added.
2.Typo mistakes has been fixed.
3.Description of the algorithms, context definition and conneection between EXP3 and EXP4 are also added.

Summary:
1.Inappropriate definition has been modified.
2.Most of the screenshot images have been deleted, only one of them is used for description in the beginning.
3.Different Value functions and equations are derived and described in Section 2.4

Additional info:
1.Add something new and reorganize the Appendix based on the instructions.

Thank you very much.
Xuanbai.

**Comment by lagrassa** [comment]
PDF updated with most requested changes and appendix is 2 pages worth of info.

The figures are still largely screenshots from lecture. Are you sure you uploaded the most recent version?

**Comment by Xuanbai-Chen** [comment]
Delete all the figures and uploaded again! Thank you very much!

**Pull request merged**
