### PR TITLE
lecture 8 b

### PR DESCRIPTION
**Pull request by luluricketts**

### CODE REVIEW

**Comment by lagrassa** [comment]
### Feedback
**Review Section**
1. Good overview of OCO in the first enumeratation. Please include the symbols we use in next to the English descriptions you provide of the steps
2. Please update W to use S just to be consistent with the lecture notation. 

**Summary Section**
1. Helpful explanations of many of the steps in the algebra, including introducing/defining mathematical tools before applying them
2. Authors need to recreate figures. In general, scribe notes need to generate their own graphics. They don't need to be polished and only need to include the information you reference in the text. If you can frame them differently or in a way that's more effective, great, but all that's required is recreating them yourself. 
2. Good work explaining the intuition (where possible) when proving the regret bound for OMD
3. Thorough geometric interpretations. When you recreate the relevant figures, you can also include labels to reference when you explain the various components. 
4. Mistake in Eq. 7. The left should just be an equal sign.
5. 2.1.1. informal language starting with "Let us substitute..." is imprecise and should be updated.  $z^{(1:t)}$ is being substituted with a function of $\theta^{(t+1)}$, not just $\theta^{(t+1)}$

**Outside Information**
N/A

### Notes for the TA
Submitted within 3 days
Did not include additional outside info.

**Review by lagrassa — CHANGES_REQUESTED** [review]
There were a lot of new concepts introduced in this lecture and then used in the derivations. These scribes introduce and then describe the intuition as well as going step-by-step in the analysis (at least as much as the lecture notes do). The main changes that need to happen are mostly to update the figures and address a typo in the math.

Please update with the requested changes by Friday 2/25

**Comment by dakshitagrawal** [comment]
Point 2 in Review Section Feedback:

We referenced the algorithm given in Lecture 6 Slide 54.

**Comment by luluricketts** [comment]
Updated figures

**Pull request merged**
