### PR TITLE
lecture 08 A

### PR DESCRIPTION
**Pull request by jasonxiang1**

### CODE REVIEW

**Comment by jasonxiang1** [comment]
Feng Xiang
Yuqing Qin

**Comment by lagrassa** [comment]
### Feedback
**Review Section**
1. Minor typo at the end of Algorithm you can remove but it's pretty clear it's a typo
1.  Good straightforward review of the algorithms and their properties
2. 
**Summary Section**
1.  First of all, good work going through all this. There were a lot of steps in the derivations. 
2.  Figure 1 is copied from the slides. In the CR, please update with your own version of the figure including the information you reference (by the way, there's a broken reference at "A visualization is shown in Figure ?? below.)
3. Similar for Figure 2 3 and 4. You don't need to recreate the figures exactly and can include the information on multiple. 
4. You went through the steps in the derivation in the regret bound for OMD. It would be helpful to include brief notes explaining the steps, which you do a little bit of but it would be good to include more (this is optional)
5. Although the derivation is mostly algebra, please include a few (let's say at least 2) descriptions of important groups of terms. In the lecture notes, these are highlighted with different colors. 

**Outside Information**
N/A

### Notes for the TA
Submitted within 3 days
Did not include additional outside info.

**Review by lagrassa — CHANGES_REQUESTED** [review]
Good work going through many steps and definitions. There was a lot of algebra as well as new concepts introduced in order to compute the OMD regret bound. A few suggestions in the comments. Please address and update by Friday 2/25. Main change is to recreate the figures. They don't need to perfect or professional-looking: just original, and enough to get the points you make across.

**Comment by jasonxiang1** [comment]
Hello. Incorporated the changes and re-committed them. Please review and let us know what you think. 

I supposed there was some confusion since the first scribe notes. From another TA's comment earlier in the semester, I thought we were not required to institute changes for a grade. Has the policy changed?

**Comment by lagrassa** [comment]
You're not "required" to in order to get credit but the expectation/hope is everyone gets 100 for these which usually requires some (usually minor) changes. We also want to keep incorrect information out of the scribe notes most importantly.

**Pull request merged**
