### PR TITLE
Add lecture 10 Scribe Notes Group A

### PR DESCRIPTION
**Pull request by mzhao98**

### CODE REVIEW

**Comment by lagrassa** [comment]
FYI, you're not supposed to screenshot figures from the lecture slides, especially if all your figures are like that. Please recreate them on your own. Preferably showing the same concepts somewhat differently but just recreating the figures is okay too.

**Comment by mzhao98** [comment]
Hi, looking at the past years scribe notes, I thought the screenshots were acceptable. However, I've removed the screenshots and replaced them with newly created ones.

**Review by lagrassa — CHANGES_REQUESTED** [review]
Mostly just needs to update broken figure references, finish the review section, and write out the intermediate step(s) in 2.2.1. Please update by Friday 3/4

### Feedback
**Review Section**
1.  Good high-level summary of the relevant content from the previous lecture.
1. Connects the part about gradient descent using the exact gradient to methods that approximate the gradient using samples
1. The review section was all very high-level and needs to expand a little more on the topics mentioned. In general, 1 page is a good length of review to aim for. In the CR, please include a brief summary of the main concepts and notation used for the review topics in the last lecture, especially those that are referenced here. For example, how does online gradient descent work, and what is the basic algorithm for SGD?

**Summary Section**
1. Although section subheadings are useful, please structure scribe notes using theorems/definitions in the future. There's a little bit of this.
1. In general, scribe notes should contain more steps than lecture notes do. In 2.2.1 for example  when calculating the vertical distance between the origin and hyperplane, please include the steps between 2. and 3.
1. Notes explain work deriving the distance between parallel lines in Figure 3.
1. 2.2.2 is referencing a figure that doesn't exist anymore. It doesn't have to perfectly match the lecture figure. Using a rectangular prism in google drawings is fine, or even a hand-drawn version.
1. Good intuition on the margins and the effect of small perturbations in the data on them.
1. Good transition from hard-margin SVM to soft-margin SVM
1. Figures 7 and 8 are changed to the kernel SVM. They're good figures to include, but you'll have to put them back in! You can also refer to them more effectively by adding your own labels.
1. The part that "we want the slack variable as small as possible" is somewhat of a over-generalization in my opinion, but could go either way.
1. 3.2 also contains 2 broken references for explaining the intuition for using the Hinge loss. If you don't want to recreate it you can also just explain the intuition.
1. Language in 3.4 is fairly informal. Perceptron algorithm doesn't ``say'' anything. What is it actually doing? You don't need to change anything in this PR, just please keep in mind for future notes. 

**Outside Information**
1. Included information on the kernel trick and for SVMs with linearly inseparable data
2. Is there a reference for this? I didn't see a citation and don't remember this from the lecture notes
### Notes for the TA
Submitted within 3 days

**Comment by mzhao98** [comment]
The changes listed have been made, thank you! Updates were pushed to https://github.com/mzhao98/16831-Spring-2022.

**Pull request merged**
