### PR TITLE
Lecture 4 notes by Group B (Mansi Agarwal and Ashwin Misra)

### PR DESCRIPTION
**Pull request by ashwin-97**

### CODE REVIEW

**Review by lagrassa — COMMENTED** [review]
### Feedback
**Review Section**
1. In the strategy for bound derivation, it would be more helpful to describe these more mathematically than the slides do. Upper bound what using the potential function? Using what?
2. Review covers mistake bounds, realizability, and justifies why we would use regret instead of loss. You could also include what the mistake bounds were, though it's good that you included the fact that one was linear in $\mathcal{H}$ and the other logarithmic.
3. Good use of both explaining something intuitively and providing a precise definition in Eq. (1) and in the explanation after.

**Summary Section**
1. Good motivation of how we come to WMA from removing the realizability assumption. 
2. Weights are penalized by $\eta$ not $-\eta$ but that's probably what you meant.
3. Working out the proof for Lemma 1 is the sort of thing you should do in scribe notes rather than writing out a sketch. You do a good job of this proving Theorem 2 and in deriving the mistake bound for WMA. I like how you justified each step of the proof in some cases to make it easier to follow the algebra.
4. You should be able to get a no-regret RWMA without an adaptive $t$. You'll explore this in the homework.

**Outside Information**
1. Links to a blog post that implements WMA that also includes some empirical results
2.Mentions multiplicative weights method. From the wording it seems to imply RWMA do
es not select decisions based on the weights. I just want to clarify they both do th
at; MW algorithm updates the weights by multiplying them instead of adding some facto
r to them.

### Notes for the TA
Submitted within 3 days
Included some outside info

**Review by lagrassa — CHANGES_REQUESTED** [review]
Please update section 1.1 according to the PR comment by Friday 2/11 and finish the proofs for the inequalities for Lemmas 1 and 4.  As a general rule of thumb, if content was brief and high level on the slides, the scribe notes are a good place to expand on it and be more specific. The rest of the report was a good example of that.

**Comment by ashwin-97** [comment]
Thank you for the comments, the scribe files are edited and committed to the repository.

**Comment by lagrassa** [comment]
Better. Thank you for addressing the comments well.

**Pull request merged**
